### ISSUE TITLE
Event's request page

### ISSUE THREAD

**Issue by playmakeric** [uOttawaSEG/project-project-group-12#15]
![image](https://github.com/user-attachments/assets/181a50e9-acc7-44d4-9e0d-b4844328ff5c)

By tuesday be done with UI - assume access to info from classes in UML

2 people cna work on this

**Comment by aaradar** [comment]
gonna make the arrayadapter hold <String> for now until we go to the actual implementation, when everyone else also finishes their pages.

**Comment by aaradar** [comment]
Page is ready to be merged once all all other pages are done. already done working on the ui part of the event requests,
