### ISSUE TITLE
Admin page 

### ISSUE THREAD

**Issue by playmakeric** [uOttawaSEG/project-project-group-12#4]
Instead of redirecting the admin to the welcome page after logging in, our app should redirects them to the admin page, where they'll be able to access all requests that are pending or have been rejected.

The layout ressembling an email inbox.  ( see image below ) 

![adminPage](https://github.com/user-attachments/assets/a721a607-1962-4143-a702-7c5066675e16)

Grading scheme from professors : 

• The Administrator can view the list of registration requests. 
• The Administrator can view the information associated with each request (the information the user entered during registration).
• The Administrator can approve or reject a registration request

**Comment by aaradar** [comment]
basically finished, but with a vertical view, just need to connect the other (DB and RegisterPage to it)
